FROM quay.io/pypa/manylinux2014_x86_64

# RUN python --version
# RUN apt
# RUN curl https://bootstrap.pypa.io/get-pip.py | python3
# RUN pip install -U setuptools-rust
# RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly --profile=minimal -y
# RUN export PATH="$HOME/.cargo/bin:$PATH"
# RUN rustup show
