[package]
name = "analyzer"
version = "0.1.0"
authors = ["romnn <contact@romnn.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.42"
ndarray = { version = "0.15.0" , features = ["approx", "rayon"]}
num = "0.4.0"
microfft = "0.4.0"
common = { path = "../common" }
proto = { path = "../proto" }
