name: python

on:
  push:
    branches:
      - master
    tags:
      - "**"
  pull_request: {}

jobs:
  build:
    name: py3.${{ matrix.python-version }} on ${{ matrix.platform || matrix.os }}
    # needs:
    #   - test
    #   - lint
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        python-version:
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"
        include:
          - os: ubuntu
            platform: linux
          - os: windows
            ls: dir

    runs-on: ${{ format('{0}-latest', matrix.os) }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Set up rust
        if: matrix.os != 'ubuntu'
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Install python dependencies
        run: pip install -U setuptools setuptools-rust wheel twine cibuildwheel

      - name: Build sdist
        if: matrix.os == 'ubuntu' && matrix.python-version == '8'
        run: |
          pip install -U setuptools-rust
          cd python && python setup.py sdist

      - name: Build ${{ matrix.platform || matrix.os }} binaries
        run: cibuildwheel --output-dir dist python
        env:
          CIBW_BUILD: "cp3${{ matrix.python-version }}-*"
          CIBW_SKIP: "*-win32"
          # CIBW_ARCHS_LINUX: x86_64 i686 aarch64 ppc64le s390x
          CIBW_ARCHS_LINUX: x86_64 i686 aarch64 s390x
          CIBW_ARCHS_MACOS: x86_64 arm64 universal2
          CIBW_PLATFORM: ${{ matrix.platform || matrix.os }}
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_COMMAND: "pytest {project}/python/tests -s"
          CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH"'
          CIBW_ENVIRONMENT_WINDOWS: 'PATH="$UserProfile\.cargo\bin;$PATH"'
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"
          CIBW_MANYLINUX_I686_IMAGE: "manylinux2014"
          # yum install tree alsa-lib-devel openssl openssl-devel -y &&
          CIBW_BEFORE_TEST_LINUX: >
            pip install -U pip pipenv setuptools setuptools-rust wheel &&
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable --profile=default -y &&
            rustup show &&
            PIPENV_PIPFILE=./python/Pipfile pipenv lock -r > requirements.txt &&
            pip install -U -r requirements.txt

          CIBW_BEFORE_BUILD_MACOS: >
            brew install tree protobuf coreutils &&
            rustup target add aarch64-apple-darwin &&
            pip install -U pip pipenv setuptools setuptools-rust wheel &&
            PIPENV_PIPFILE=./python/Pipfile pipenv lock -r > requirements.txt &&
            pip install -U -r requirements.txt &&
            rm -r python/disco-src &&
            cp -r disco python/disco-src &&
            cp -r proto python/proto &&
            tree -I 'node_modules|target|build' python

          CIBW_BEFORE_BUILD_WINDOWS: >
            choco install tree &&
            python -m pip uninstall -y pip &&
            python -m ensurepip &&
            python -m pip install -U pip &&
            pip install -U pip pipenv setuptools setuptools-rust wheel &&
            setx PIPENV_PIPFILE ./python/Pipfile &&
            pipenv lock -r > requirements.txt &&
            pip install -U -r requirements.txt &&
            rm python/disco-src &&
            cp -r disco python/disco-src &&
            cp -r proto python/proto

          CIBW_BEFORE_BUILD_LINUX: >
            yum install tree protobuf alsa-lib-devel gcc libffi-devel python-devel openssl openssl-devel -y &&
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable --profile=default -y &&
            rustup show &&
            pip install -U pip pipenv setuptools setuptools-rust wheel &&
            PIPENV_PIPFILE=./python/Pipfile pipenv lock -r > requirements.txt &&
            pip install -U -r requirements.txt &&
            rm python/disco-src &&
            cp -r disco python/disco-src &&
            cp -r proto python/proto &&
            tree -I 'node_modules|target|build' python

      - name: Build windows 32bit binaries
        if: matrix.os == 'windows'
        run: cibuildwheel --output-dir dist python
        env:
          CIBW_BUILD: "cp3${{ matrix.python-version }}-win32"
          CIBW_PLATFORM: windows
          CIBW_ARCHS_WINDOWS: x86 AMD64
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_COMMAND: "pytest {project}/tests -s"
          CIBW_ENVIRONMENT: 'PATH="$UserProfile\.cargo\bin;$PATH"'
          CIBW_BEFORE_BUILD: >
            rustup toolchain install nightly-i686-pc-windows-msvc &&
            rustup default nightly-i686-pc-windows-msvc &&
            rustup override set nightly-i686-pc-windows-msvc &&
            rustup show &&
            python -m pip uninstall -y pip &&
            python -m ensurepip &&
            python -m pip install -U pip &&
            pip install -U pip pipenv setuptools setuptools-rust wheel &&
            setx PIPENV_PIPFILE ./python/Pipfile &&
            pipenv lock -r > requirements.txt &&
            pip install -U -r requirements.txt &&
            rm python/disco-src &&
            cp -r disco python/disco-src &&
            cp -r proto python/proto

      - name: List dist files
        run: ${{ matrix.ls || 'ls -lh' }} dist/

      - name: twine check
        run: twine check dist/*

    # - name: upload to pypi
    #   if: startsWith(github.ref, 'refs/tags/')
    #   run: twine upload dist/*
    #   env:
    #     TWINE_USERNAME: __token__
    #     TWINE_PASSWORD: ${{ secrets.pypi_token }}
